name: Build and Tag Tably-Core

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for tags
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build library
        run: npm run build:lib
        
      - name: Commit built files
        if: github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/
          git commit -m "Build library for distribution" || exit 0
          git push || exit 0
        
      - name: Create version tag
        if: github.ref == 'refs/heads/main'
        run: |
          # Create timestamp-based version
          VERSION="v$(date +%Y%m%d-%H%M%S)"
          echo "Creating tag: $VERSION"
          
          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Create and push tag
          git tag -a "$VERSION" -m "Auto-build $VERSION"
          git push origin "$VERSION"
          
          echo "Created tag: $VERSION"
          
      - name: Trigger environment updates
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Triggering updates for all environments..."
          echo "Version: $VERSION"
          
          # ========================================
          # ADD NEW ENVIRONMENTS HERE
          # ========================================
          # Copy the curl command below and change:
          # 1. Repository name (e.g., Ebrahem1999/main-staging)
          # 2. Event type (e.g., tably-core-updated-staging)
          # ========================================
          
          # PRODUCTION ENVIRONMENT
          echo "Triggering PRODUCTION update..."
          RESPONSE_PROD=$(curl -s -w "\n%{http_code}" -X POST \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Ebrahem1999/main/dispatches \
            -d '{"event_type":"tably-core-updated","client_payload":{"version":"'$VERSION'"}}')
          
          HTTP_CODE_PROD=$(echo "$RESPONSE_PROD" | tail -n1)
          RESPONSE_BODY_PROD=$(echo "$RESPONSE_PROD" | head -n -1)
          
          echo "PRODUCTION - HTTP Status: $HTTP_CODE_PROD"
          echo "PRODUCTION - Response: $RESPONSE_BODY_PROD"
          
          if [ "$HTTP_CODE_PROD" = "204" ]; then
            echo "✅ Successfully triggered PRODUCTION update"
          else
            echo "❌ Failed to trigger PRODUCTION update"
          fi
          
          # ========================================
          # STAGING ENVIRONMENT (EXAMPLE)
          # ========================================
          # Uncomment and modify the lines below to add staging environment:
          #
          # echo "Triggering STAGING update..."
          # RESPONSE_STAGING=$(curl -s -w "\n%{http_code}" -X POST \
          #   -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          #   -H "Accept: application/vnd.github.v3+json" \
          #   https://api.github.com/repos/Ebrahem1999/main-staging/dispatches \
          #   -d '{"event_type":"tably-core-updated-staging","client_payload":{"version":"'$VERSION'"}}')
          #
          # HTTP_CODE_STAGING=$(echo "$RESPONSE_STAGING" | tail -n1)
          # if [ "$HTTP_CODE_STAGING" = "204" ]; then
          #   echo "✅ Successfully triggered STAGING update"
          # else
          #   echo "❌ Failed to trigger STAGING update"
          # fi
          
          # ========================================
          # DEVELOPMENT ENVIRONMENT (EXAMPLE)
          # ========================================
          # Uncomment and modify the lines below to add development environment:
          #
          # echo "Triggering DEVELOPMENT update..."
          # RESPONSE_DEV=$(curl -s -w "\n%{http_code}" -X POST \
          #   -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          #   -H "Accept: application/vnd.github.v3+json" \
          #   https://api.github.com/repos/Ebrahem1999/main-dev/dispatches \
          #   -d '{"event_type":"tably-core-updated-dev","client_payload":{"version":"'$VERSION'"}}')
          #
          # HTTP_CODE_DEV=$(echo "$RESPONSE_DEV" | tail -n1)
          # if [ "$HTTP_CODE_DEV" = "204" ]; then
          #   echo "✅ Successfully triggered DEVELOPMENT update"
          # else
          #   echo "❌ Failed to trigger DEVELOPMENT update"
          # fi
          
          # ========================================
          # ADD MORE ENVIRONMENTS AS NEEDED
          # ========================================
          # Follow the same pattern:
          # 1. Copy the curl command
          # 2. Change repository name
          # 3. Change event type
          # 4. Add success/failure logging
          # ========================================